# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Application\:
        resource: '%kernel.project_dir%/src/Application'

    Application\Http\:
        resource: '%kernel.project_dir%/src/Application/Http'
        tags: ['controller.service_arguments']

    Domain\:
        resource: '%kernel.project_dir%/src/Domain'

    Infrastructure\:
        resource: '%kernel.project_dir%/src/Infrastructure'
        exclude: '%kernel.project_dir%/src/Infrastructure/Doctrine/Migrations'

    Domain\User\UserRepositoryInterface:
        alias: Infrastructure\User\UserRepository

    Domain\Beer\BeerRepositoryInterface:
        alias: Infrastructure\Beer\BeerRepository

    Domain\Beer\Browse\BrowseBeerRepositoryInterface:
        alias: Infrastructure\Beer\BeerRepository

    Domain\Beer\Import\ExternalBeerRepositoryInterface:
        alias: Infrastructure\Beer\Import\ExternalBeerRepository

    Infrastructure\Response\ApiResponseFactory:
        arguments:
            -
                'Domain\Beer\Beer': 'Application\Resource\BeerResource'
                'Application\Security\Jwt\Token': 'Application\Resource\TokenResource'

    Infrastructure\Response\ApiResponseSubscriber:
        arguments:
            $statuses:
                100000: { title: 'Forbidden', status: 403 }
                1000: { title: 'Bad Request', status: 400 }
                1: { title: 'Not Found', status: 404 }
                2: { title: 'Unprocessable Entity', status: 422 }
                3: { title: 'Conflict', status: 409 }

    Infrastructure\Security\Jwt\TokenFactory:
        arguments:
            $privateKey: '%kernel.secret%'

    Infrastructure\Security\Jwt\TokenVerifier:
        arguments:
            $privateKey: '%kernel.secret%'

    Infrastructure\Request\ClientInterface:
        alias: Infrastructure\Request\CurlClient
